package com.example.prasanna.trainscheduleapp.Utilities;

import com.example.prasanna.trainscheduleapp.Models.TrainStation;
import java.util.ArrayList;

/**
 * Created by prasanna on 5/30/17.
 */

public abstract class TrainStations {
    private static ArrayList<TrainStation> arrTrainStation;

    public static ArrayList<TrainStation> getStationArray() {
        arrTrainStation = new ArrayList<>();
        arrTrainStation.add(new TrainStation("3", "ABANPOLA"));
        arrTrainStation.add(new TrainStation("410", "ADAGALA"));
        arrTrainStation.add(new TrainStation("11", "AHANGAMA"));
        arrTrainStation.add(new TrainStation("18", "AHUNGALLE"));
        arrTrainStation.add(new TrainStation("13", "AKBOPURA"));
        arrTrainStation.add(new TrainStation("7", "AKURALA"));
        arrTrainStation.add(new TrainStation("22", "ALAWATUPITIYA"));
        arrTrainStation.add(new TrainStation("9", "ALAWWA"));
        arrTrainStation.add(new TrainStation("329", "ALUTH AMBALAMA"));
        arrTrainStation.add(new TrainStation("8", "ALUTHGAMA"));
        arrTrainStation.add(new TrainStation("1", "AMBALANGODA"));
        arrTrainStation.add(new TrainStation("2", "AMBEWELA"));
        arrTrainStation.add(new TrainStation("14", "AMBEYPUSSA"));
        arrTrainStation.add(new TrainStation("19", "ANAWILUNDAWA"));
        arrTrainStation.add(new TrainStation("10", "ANDADOLA"));
        arrTrainStation.add(new TrainStation("5", "ANGAMPITIYA"));
        arrTrainStation.add(new TrainStation("4", "ANGULANA"));
        arrTrainStation.add(new TrainStation("12", "ANURADHAPURA"));
        arrTrainStation.add(new TrainStation("15", "ANURADHAPURA TOWN"));
        arrTrainStation.add(new TrainStation("6", "ARACHCHIKATTUWA"));
        arrTrainStation.add(new TrainStation("343", "ARAPATHGAMA"));
        arrTrainStation.add(new TrainStation("16", "ARUKKUWATTE"));
        arrTrainStation.add(new TrainStation("17", "ASELAPURA"));
        arrTrainStation.add(new TrainStation("467", "ASGIRIYA"));
        arrTrainStation.add(new TrainStation("21", "AUKANA"));
        arrTrainStation.add(new TrainStation("20", "AVISSAWELLA"));
        arrTrainStation.add(new TrainStation("23", "BADULLA"));
        arrTrainStation.add(new TrainStation("31", "BALANA"));
        arrTrainStation.add(new TrainStation("34", "BALAPITIYA"));
        arrTrainStation.add(new TrainStation("35", "BAMBALAPITIYA"));
        arrTrainStation.add(new TrainStation("25", "BANDARAWELA"));
        arrTrainStation.add(new TrainStation("475", "Bandirippuwa"));
        arrTrainStation.add(new TrainStation("28", "BANGADENIYA"));
        arrTrainStation.add(new TrainStation("39", "BASELINE ROAD"));
        arrTrainStation.add(new TrainStation("33", "BATTALUOYA"));
        arrTrainStation.add(new TrainStation("24", "BATTICALOA"));
        arrTrainStation.add(new TrainStation("41", "BATUWATTE"));
        arrTrainStation.add(new TrainStation("26", "BEMMULLA"));
        arrTrainStation.add(new TrainStation("32", "BENTOTA"));
        arrTrainStation.add(new TrainStation("36", "BERUWALA"));
        arrTrainStation.add(new TrainStation("30", "BOLAWATTE"));
        arrTrainStation.add(new TrainStation("38", "BOOSSA"));
        arrTrainStation.add(new TrainStation("37", "BORELESSA"));
        arrTrainStation.add(new TrainStation("40", "BOTALE"));
        arrTrainStation.add(new TrainStation("27", "BULUGAHAGODA"));
        arrTrainStation.add(new TrainStation("29", "BUTHGAMUWA"));
        arrTrainStation.add(new TrainStation("398", "CHAVAKACHCHERI"));
        arrTrainStation.add(new TrainStation("371", "CHEDDIIKULAM"));
        arrTrainStation.add(new TrainStation("44", "CHILAW"));
        arrTrainStation.add(new TrainStation("43", "CHINA BEY"));
        arrTrainStation.add(new TrainStation("423", "CHUNNAKAM"));
        arrTrainStation.add(new TrainStation("61", "COLOMBO FORT"));
        arrTrainStation.add(new TrainStation("46", "COTTA ROAD"));
        arrTrainStation.add(new TrainStation("53", "DARALUWA"));
        arrTrainStation.add(new TrainStation("457", "DEC"));
        arrTrainStation.add(new TrainStation("54", "DEHIWALA"));
        arrTrainStation.add(new TrainStation("337", "Dekinda"));
        arrTrainStation.add(new TrainStation("47", "DEMATAGODA"));
        arrTrainStation.add(new TrainStation("48", "DEMODARA"));
        arrTrainStation.add(new TrainStation("52", "DEWAPURAM"));
        arrTrainStation.add(new TrainStation("417", "DEWEDDA"));
        arrTrainStation.add(new TrainStation("50", "DIYATALAWA"));
        arrTrainStation.add(new TrainStation("51", "DODANDUWA"));
        arrTrainStation.add(new TrainStation("60", "EGODA UYANA"));
        arrTrainStation.add(new TrainStation("395", "ELIPHANT PASS"));
        arrTrainStation.add(new TrainStation("57", "ELLE"));
        arrTrainStation.add(new TrainStation("401", "ELUTHUMATTUVAL"));
        arrTrainStation.add(new TrainStation("341", "ELWALA"));
        arrTrainStation.add(new TrainStation("55", "ENDERAMULLA"));
        arrTrainStation.add(new TrainStation("56", "ERATTAPERIYAKULAM"));
        arrTrainStation.add(new TrainStation("59", "ERAVUR"));
        arrTrainStation.add(new TrainStation("58", "ERUKKALAM PENDU"));
        arrTrainStation.add(new TrainStation("104", "FREE TRADE ZONE"));
        arrTrainStation.add(new TrainStation("64", "GALABODA"));
        arrTrainStation.add(new TrainStation("69", "GALGAMUWA"));
        arrTrainStation.add(new TrainStation("68", "GALLE"));
        arrTrainStation.add(new TrainStation("62", "GALLELLA"));
        arrTrainStation.add(new TrainStation("74", "GALOYA JUNCTION"));
        arrTrainStation.add(new TrainStation("70", "GAMMANA"));
        arrTrainStation.add(new TrainStation("75", "GAMPAHA"));
        arrTrainStation.add(new TrainStation("76", "GAMPOLA"));
        arrTrainStation.add(new TrainStation("71", "GANEGODA"));
        arrTrainStation.add(new TrainStation("63", "GANEMULLA"));
        arrTrainStation.add(new TrainStation("73", "GANEWATTE"));
        arrTrainStation.add(new TrainStation("479", "Gangathilaka"));
        arrTrainStation.add(new TrainStation("65", "GANGODA"));
        arrTrainStation.add(new TrainStation("440", "GANTALAWA"));
        arrTrainStation.add(new TrainStation("66", "GELIOYA"));
        arrTrainStation.add(new TrainStation("72", "GINTHOTA"));
        arrTrainStation.add(new TrainStation("476", "GIRAMBE"));
        arrTrainStation.add(new TrainStation("77", "GIRAMBE"));
        arrTrainStation.add(new TrainStation("67", "GODAGAMA"));
        arrTrainStation.add(new TrainStation("79", "GREAT WESTERN"));
        arrTrainStation.add(new TrainStation("81", "HABARADUWA"));
        arrTrainStation.add(new TrainStation("82", "HABARANA"));
        arrTrainStation.add(new TrainStation("456", "Hadiriwalana"));
        arrTrainStation.add(new TrainStation("84", "HALIELA"));
        arrTrainStation.add(new TrainStation("92", "HAPUTALE"));
        arrTrainStation.add(new TrainStation("80", "HATAMUNA"));
        arrTrainStation.add(new TrainStation("87", "HATARAS KOTUWA"));
        arrTrainStation.add(new TrainStation("96", "HATTON"));
        arrTrainStation.add(new TrainStation("89", "HEEL OYA"));
        arrTrainStation.add(new TrainStation("83", "HEENDENIYA"));
        arrTrainStation.add(new TrainStation("91", "HETTIMULLA"));
        arrTrainStation.add(new TrainStation("86", "HIKKADUWA"));
        arrTrainStation.add(new TrainStation("93", "HINGURAKGODA"));
        arrTrainStation.add(new TrainStation("444", "HINGURALA"));
        arrTrainStation.add(new TrainStation("94", "HIRIYALA"));
        arrTrainStation.add(new TrainStation("90", "HOMAGAMA"));
        arrTrainStation.add(new TrainStation("85", "HOMAGAMA HOSPITAL"));
        arrTrainStation.add(new TrainStation("95", "HORAPE"));
        arrTrainStation.add(new TrainStation("88", "HORIWIALA"));
        arrTrainStation.add(new TrainStation("97", "HUNUPITIYA"));
        arrTrainStation.add(new TrainStation("98", "HYINPORT"));
        arrTrainStation.add(new TrainStation("100", "IDALGASINNA"));
        arrTrainStation.add(new TrainStation("101", "IHALAGAMA"));
        arrTrainStation.add(new TrainStation("102", "IHALAKOTTE"));
        arrTrainStation.add(new TrainStation("105", "IHALAWATAWALA"));
        arrTrainStation.add(new TrainStation("99", "INDURUWA"));
        arrTrainStation.add(new TrainStation("103", "INGURUOYA"));
        arrTrainStation.add(new TrainStation("428", "INUVIL"));
        arrTrainStation.add(new TrainStation("107", "JA-ELA"));
        arrTrainStation.add(new TrainStation("400", "JAFFNA"));
        arrTrainStation.add(new TrainStation("106", "JAYANTHIPURA"));
        arrTrainStation.add(new TrainStation("338", "KACHCHERI HALL"));
        arrTrainStation.add(new TrainStation("114", "KADADASI NAGAR"));
        arrTrainStation.add(new TrainStation("128", "KADIGAMUWA"));
        arrTrainStation.add(new TrainStation("120", "KADUGANNAWA"));
        arrTrainStation.add(new TrainStation("113", "KADUGODA"));
        arrTrainStation.add(new TrainStation("480", "Kahatapitiya"));
        arrTrainStation.add(new TrainStation("152", "KAHAWA"));
        arrTrainStation.add(new TrainStation("154", "KAKKAPALLIYA"));
        arrTrainStation.add(new TrainStation("127", "KALAWEWA"));
        arrTrainStation.add(new TrainStation("123", "KALKUDAH"));
        arrTrainStation.add(new TrainStation("147", "KALUTARA NORTH"));
        arrTrainStation.add(new TrainStation("148", "KALUTARA SOUTH"));
        arrTrainStation.add(new TrainStation("130", "KAMBURUGAMUWA"));
        arrTrainStation.add(new TrainStation("108", "KANDANA"));
        arrTrainStation.add(new TrainStation("119", "KANDEGODA"));
        arrTrainStation.add(new TrainStation("115", "KANDY"));
        arrTrainStation.add(new TrainStation("424", "KANKESANTHURAI"));
        arrTrainStation.add(new TrainStation("132", "KANTALE"));
        arrTrainStation.add(new TrainStation("110", "KAPUWATTE"));
        arrTrainStation.add(new TrainStation("139", "KARADIPUWAL"));
        arrTrainStation.add(new TrainStation("146", "KATHALUWA"));
        arrTrainStation.add(new TrainStation("109", "KATTUWA"));
        arrTrainStation.add(new TrainStation("144", "KATUGASTOTA"));
        arrTrainStation.add(new TrainStation("468", "KATUGASTOTA     ROAD"));
        arrTrainStation.add(new TrainStation("150", "KATUGODA"));
        arrTrainStation.add(new TrainStation("122", "KATUKURUNDA"));
        arrTrainStation.add(new TrainStation("42", "KATUNAYAKA AIRPORT"));
        arrTrainStation.add(new TrainStation("145", "KATUNAYAKE"));
        arrTrainStation.add(new TrainStation("117", "KEENAWALA"));
        arrTrainStation.add(new TrainStation("141", "KEKIRAWA"));
        arrTrainStation.add(new TrainStation("124", "KELANIYA"));
        arrTrainStation.add(new TrainStation("333", "KILINOCHCHI"));
        arrTrainStation.add(new TrainStation("133", "KINIGAMA"));
        arrTrainStation.add(new TrainStation("447", "KIRINDIWELA"));
        arrTrainStation.add(new TrainStation("138", "KIRULAPANA"));
        arrTrainStation.add(new TrainStation("116", "KITAL ELLE"));
        arrTrainStation.add(new TrainStation("111", "KOCHCHIKADE"));
        arrTrainStation.add(new TrainStation("397", "KODIKAMAM"));
        arrTrainStation.add(new TrainStation("134", "KOGGALA"));
        arrTrainStation.add(new TrainStation("474", "KOHOMBILIWALA"));
        arrTrainStation.add(new TrainStation("429", "KOKUVIL"));
        arrTrainStation.add(new TrainStation("126", "KOLLUPITIYA"));
        arrTrainStation.add(new TrainStation("453", "KOLONNAWA"));
        arrTrainStation.add(new TrainStation("125", "KOLONNAWA"));
        arrTrainStation.add(new TrainStation("140", "KOMPANNAVEDIYA"));
        arrTrainStation.add(new TrainStation("422", "KONDAVIL"));
        arrTrainStation.add(new TrainStation("135", "KONWEWA"));
        arrTrainStation.add(new TrainStation("136", "KORALAWELLA"));
        arrTrainStation.add(new TrainStation("143", "KOSGAMA"));
        arrTrainStation.add(new TrainStation("112", "KOSGODA"));
        arrTrainStation.add(new TrainStation("121", "KOSHINNA"));
        arrTrainStation.add(new TrainStation("118", "KOTAGALA"));
        arrTrainStation.add(new TrainStation("137", "KOTTAWA"));
        arrTrainStation.add(new TrainStation("153", "KUDA WAWA"));
        arrTrainStation.add(new TrainStation("149", "KUDAHAKAPOLA"));
        arrTrainStation.add(new TrainStation("131", "KUMARAKANDA"));
        arrTrainStation.add(new TrainStation("129", "KUMBALGAMA"));
        arrTrainStation.add(new TrainStation("408", "KURAHANHENAGAMA"));
        arrTrainStation.add(new TrainStation("151", "KURANA"));
        arrTrainStation.add(new TrainStation("142", "KURUNEGALA"));
        arrTrainStation.add(new TrainStation("158", "LAKSAUYANA"));
        arrTrainStation.add(new TrainStation("155", "LIYANAGEMULLA"));
        arrTrainStation.add(new TrainStation("334", "LIYANWALA"));
        arrTrainStation.add(new TrainStation("156", "LUNAWA"));
        arrTrainStation.add(new TrainStation("157", "LUNUWILA"));
        arrTrainStation.add(new TrainStation("181", "MADAMPAGAMA"));
        arrTrainStation.add(new TrainStation("161", "MADAMPE"));
        arrTrainStation.add(new TrainStation("372", "MADHU ROAD"));
        arrTrainStation.add(new TrainStation("174", "MADURANKULIYA"));
        arrTrainStation.add(new TrainStation("472", "Magalegoda"));
        arrTrainStation.add(new TrainStation("393", "MAGALEGODA"));
        arrTrainStation.add(new TrainStation("167", "MAGGONA"));
        arrTrainStation.add(new TrainStation("452", "MAGULEGODA"));
        arrTrainStation.add(new TrainStation("190", "MAHAIYAWA"));
        arrTrainStation.add(new TrainStation("159", "MAHARAGAMA"));
        arrTrainStation.add(new TrainStation("170", "MAHO"));
        arrTrainStation.add(new TrainStation("182", "MALAPALLE"));
        arrTrainStation.add(new TrainStation("427", "MALLAKAM"));
        arrTrainStation.add(new TrainStation("183", "MANAMPITIYA"));
        arrTrainStation.add(new TrainStation("165", "MANGALAELIYA"));
        arrTrainStation.add(new TrainStation("331", "MANKULAM"));
        arrTrainStation.add(new TrainStation("434", "MANNAR"));
        arrTrainStation.add(new TrainStation("179", "MANUWANGAMA"));
        arrTrainStation.add(new TrainStation("160", "MARADANA"));
        arrTrainStation.add(new TrainStation("462", "MARAKONA"));
        arrTrainStation.add(new TrainStation("454", "MARALUWEWA"));
        arrTrainStation.add(new TrainStation("186", "MATALE"));
        arrTrainStation.add(new TrainStation("187", "MATARA"));
        arrTrainStation.add(new TrainStation("432", "MATHOTTAM"));
        arrTrainStation.add(new TrainStation("466", "MAVILMADA"));
        arrTrainStation.add(new TrainStation("425", "MAVITTAPURAM"));
        arrTrainStation.add(new TrainStation("163", "MEDAGAMA"));
        arrTrainStation.add(new TrainStation("189", "MEDAWACHCHIYA"));
        arrTrainStation.add(new TrainStation("421", "MEDDEGAMA"));
        arrTrainStation.add(new TrainStation("464", "MEEGAMMANA"));
        arrTrainStation.add(new TrainStation("164", "MEEGODA"));
        arrTrainStation.add(new TrainStation("403", "MEESALAI"));
        arrTrainStation.add(new TrainStation("188", "MHA INDURUWA"));
        arrTrainStation.add(new TrainStation("162", "MIDIGAMA"));
        arrTrainStation.add(new TrainStation("169", "MIHINTALE"));
        arrTrainStation.add(new TrainStation("168", "MIHINTALE JUNCTION"));
        arrTrainStation.add(new TrainStation("173", "MINNERIYA"));
        arrTrainStation.add(new TrainStation("171", "MIRIGAMA"));
        arrTrainStation.add(new TrainStation("409", "MIRIHANPITIGAMA"));
        arrTrainStation.add(new TrainStation("172", "MIRISSA"));
        arrTrainStation.add(new TrainStation("443", "MIRISWATTA"));
        arrTrainStation.add(new TrainStation("402", "MIRUSUVIL"));
        arrTrainStation.add(new TrainStation("177", "MOLLIPATANA"));
        arrTrainStation.add(new TrainStation("176", "MORAGOLLAGAMA"));
        arrTrainStation.add(new TrainStation("175", "MORAKELE"));
        arrTrainStation.add(new TrainStation("184", "MORATUWA"));
        arrTrainStation.add(new TrainStation("439", "MOUNT LAVINIA"));
        arrTrainStation.add(new TrainStation("180", "MUNDAL"));
        arrTrainStation.add(new TrainStation("332", "MURIKANDY"));
        arrTrainStation.add(new TrainStation("431", "MURUNKAN"));
        arrTrainStation.add(new TrainStation("185", "MUTHTHETTUGALA"));
        arrTrainStation.add(new TrainStation("191", "NAGOLLAGAMA"));
        arrTrainStation.add(new TrainStation("196", "NAILIYA"));
        arrTrainStation.add(new TrainStation("197", "NANUOYA"));
        arrTrainStation.add(new TrainStation("195", "NARAHENPITA"));
        arrTrainStation.add(new TrainStation("192", "NATTANDIYA"));
        arrTrainStation.add(new TrainStation("399", "NAVATKULI"));
        arrTrainStation.add(new TrainStation("201", "NAWALAPITIYA"));
        arrTrainStation.add(new TrainStation("202", "NAWINNA"));
        arrTrainStation.add(new TrainStation("194", "NEGAMA"));
        arrTrainStation.add(new TrainStation("193", "NEGOMBO"));
        arrTrainStation.add(new TrainStation("415", "NELUMPATHGAMA"));
        arrTrainStation.add(new TrainStation("199", "NELUMPOKUNA"));
        arrTrainStation.add(new TrainStation("370", "NERIYAKULAM"));
        arrTrainStation.add(new TrainStation("198", "NOORANAGAR"));
        arrTrainStation.add(new TrainStation("200", "NUGEGODA"));
        arrTrainStation.add(new TrainStation("203", "OHIYA"));
        arrTrainStation.add(new TrainStation("204", "OMANTHAI"));
        arrTrainStation.add(new TrainStation("208", "PADUKKA"));
        arrTrainStation.add(new TrainStation("420", "PAHALAWARDHANA"));
        arrTrainStation.add(new TrainStation("238", "PALAVI"));
        arrTrainStation.add(new TrainStation("396", "PALLAI"));
        arrTrainStation.add(new TrainStation("465", "PALLE TALAVINNA"));
        arrTrainStation.add(new TrainStation("219", "PALLEWALA"));
        arrTrainStation.add(new TrainStation("237", "PALUGASWEWA"));
        arrTrainStation.add(new TrainStation("223", "PANADURA"));
        arrTrainStation.add(new TrainStation("224", "PANAGODA"));
        arrTrainStation.add(new TrainStation("226", "PANALEEYA"));
        arrTrainStation.add(new TrainStation("233", "PANGIRIWATTA"));
        arrTrainStation.add(new TrainStation("205", "PANNIPITIYA"));
        arrTrainStation.add(new TrainStation("216", "PARAKUMPURA"));
        arrTrainStation.add(new TrainStation("394", "PARANTHAN"));
        arrTrainStation.add(new TrainStation("213", "PARASANGAHAWEWA"));
        arrTrainStation.add(new TrainStation("209", "PATAGAMGODA"));
        arrTrainStation.add(new TrainStation("236", "PATHANPHA"));
        arrTrainStation.add(new TrainStation("230", "PATTIPOLA"));
        arrTrainStation.add(new TrainStation("211", "PAYAGALA NORTH"));
        arrTrainStation.add(new TrainStation("212", "PAYAGALA SOUTH"));
        arrTrainStation.add(new TrainStation("232", "PEMROSE"));
        arrTrainStation.add(new TrainStation("207", "PERADENIYA"));
        arrTrainStation.add(new TrainStation("459", "PERAKUMPURA"));
        arrTrainStation.add(new TrainStation("231", "PERALANDA"));
        arrTrainStation.add(new TrainStation("227", "PERIYANAGAVILLU"));
        arrTrainStation.add(new TrainStation("436", "PESALAI"));
        arrTrainStation.add(new TrainStation("217", "PILIDUWA"));
        arrTrainStation.add(new TrainStation("222", "PILIMATALAWA"));
        arrTrainStation.add(new TrainStation("416", "PINNAGOLLA"));
        arrTrainStation.add(new TrainStation("228", "PINNAWALA"));
        arrTrainStation.add(new TrainStation("214", "PINWATTE"));
        arrTrainStation.add(new TrainStation("210", "PIYADIGAMA"));
        arrTrainStation.add(new TrainStation("240", "PIYAGAMA"));
        arrTrainStation.add(new TrainStation("477", "Polgaha Anga"));
        arrTrainStation.add(new TrainStation("218", "POLGAHAWELA"));
        arrTrainStation.add(new TrainStation("220", "POLONNARUWA"));
        arrTrainStation.add(new TrainStation("221", "POLWATHUMODARA"));
        arrTrainStation.add(new TrainStation("229", "POONEWA"));
        arrTrainStation.add(new TrainStation("419", "PORAPOLA"));
        arrTrainStation.add(new TrainStation("418", "PORAPOLA JUNC."));
        arrTrainStation.add(new TrainStation("234", "POTUHERA"));
        arrTrainStation.add(new TrainStation("206", "PULACHCHIKULAM"));
        arrTrainStation.add(new TrainStation("330", "PULIYANKULAM"));
        arrTrainStation.add(new TrainStation("225", "PUNANI"));
        arrTrainStation.add(new TrainStation("406", "PUNKANKULAM"));
        arrTrainStation.add(new TrainStation("235", "PUTTALAM"));
        arrTrainStation.add(new TrainStation("445", "PUWAKPITIYA"));
        arrTrainStation.add(new TrainStation("446", "PUWAKPITIYA TOWN"));
        arrTrainStation.add(new TrainStation("243", "RADELLA"));
        arrTrainStation.add(new TrainStation("246", "RAGAMA"));
        arrTrainStation.add(new TrainStation("241", "RAMBUKKANA"));
        arrTrainStation.add(new TrainStation("247", "RANAMUGGAMUWA"));
        arrTrainStation.add(new TrainStation("245", "RANDENIGAMA"));
        arrTrainStation.add(new TrainStation("249", "RATHGAMA"));
        arrTrainStation.add(new TrainStation("248", "RATMALANA"));
        arrTrainStation.add(new TrainStation("244", "REDEETHENNA"));
        arrTrainStation.add(new TrainStation("242", "RICHMOND HILL"));
        arrTrainStation.add(new TrainStation("250", "ROSELLA"));
        arrTrainStation.add(new TrainStation("251", "SALIYAPURA"));
        arrTrainStation.add(new TrainStation("404", "SANKATHANAI"));
        arrTrainStation.add(new TrainStation("257", "SARASAVIUYANA"));
        arrTrainStation.add(new TrainStation("259", "SAWARANA"));
        arrTrainStation.add(new TrainStation("252", "SECRETARTAT HALT"));
        arrTrainStation.add(new TrainStation("253", "SEEDUWA"));
        arrTrainStation.add(new TrainStation("255", "SEENIGAMA"));
        arrTrainStation.add(new TrainStation("254", "SENARATHGAMA"));
        arrTrainStation.add(new TrainStation("258", "SEVANAPITIYA"));
        arrTrainStation.add(new TrainStation("339", "SIYABALANGAMUWA"));
        arrTrainStation.add(new TrainStation("260", "SIYALANGAMUWA"));
        arrTrainStation.add(new TrainStation("256", "SRAWASTHIPURA"));
        arrTrainStation.add(new TrainStation("437", "TALAIMANNAR"));
        arrTrainStation.add(new TrainStation("438", "TALAIMANNAR PIER"));
        arrTrainStation.add(new TrainStation("270", "TALAWA"));
        arrTrainStation.add(new TrainStation("269", "TALAWAKELE"));
        arrTrainStation.add(new TrainStation("276", "TALAWATTEGEDARA"));
        arrTrainStation.add(new TrainStation("461", "TAWALANOYA"));
        arrTrainStation.add(new TrainStation("426", "TELLIPALLAI"));
        arrTrainStation.add(new TrainStation("277", "TELWATTE"));
        arrTrainStation.add(new TrainStation("262", "TEMBLIGALA"));
        arrTrainStation.add(new TrainStation("405", "THACHANTHOPPU"));
        arrTrainStation.add(new TrainStation("271", "THALPE"));
        arrTrainStation.add(new TrainStation("414", "THAMBAGALLA"));
        arrTrainStation.add(new TrainStation("263", "THAMBUTTEGAMA"));
        arrTrainStation.add(new TrainStation("450", "THAMPALAKAMAM"));
        arrTrainStation.add(new TrainStation("265", "THANDIKULAM"));
        arrTrainStation.add(new TrainStation("433", "THIIRUKETHEESWARAM"));
        arrTrainStation.add(new TrainStation("267", "THILLADIYA"));
        arrTrainStation.add(new TrainStation("272", "THIRANAGAMA"));
        arrTrainStation.add(new TrainStation("435", "THODDAVELI"));
        arrTrainStation.add(new TrainStation("455", "Thuruliyagama"));
        arrTrainStation.add(new TrainStation("268", "TIMBIRIYAGEDARA"));
        arrTrainStation.add(new TrainStation("274", "TISMALPOLA"));
        arrTrainStation.add(new TrainStation("273", "TRAIN HALT 01"));
        arrTrainStation.add(new TrainStation("264", "TRINCOMALEE"));
        arrTrainStation.add(new TrainStation("275", "TUDELLA"));
        arrTrainStation.add(new TrainStation("266", "TUMMODARA"));
        arrTrainStation.add(new TrainStation("278", "UDATALAWINNA"));
        arrTrainStation.add(new TrainStation("285", "UDATHTHAWALA"));
        arrTrainStation.add(new TrainStation("281", "UDHAMULLA"));
        arrTrainStation.add(new TrainStation("413", "UDUGODAGAMA"));
        arrTrainStation.add(new TrainStation("279", "UDUWARA"));
        arrTrainStation.add(new TrainStation("280", "UGGALLA"));
        arrTrainStation.add(new TrainStation("282", "UKUWELA"));
        arrTrainStation.add(new TrainStation("283", "ULAPANE"));
        arrTrainStation.add(new TrainStation("284", "UNAWATUNA"));
        arrTrainStation.add(new TrainStation("451", "Urugodawattha"));
        arrTrainStation.add(new TrainStation("412", "UYANGALLA"));
        arrTrainStation.add(new TrainStation("286", "VALACHCHENEI"));
        arrTrainStation.add(new TrainStation("288", "VANDARAMULLAI"));
        arrTrainStation.add(new TrainStation("289", "VAVUNIYA"));
        arrTrainStation.add(new TrainStation("287", "VEYANGODA"));
        arrTrainStation.add(new TrainStation("340", "VIRALMURIPPUWA"));
        arrTrainStation.add(new TrainStation("292", "WADDUWA"));
        arrTrainStation.add(new TrainStation("295", "WAGA"));
        arrTrainStation.add(new TrainStation("299", "WAIKKALA"));
        arrTrainStation.add(new TrainStation("296", "WALAHAPITIYA"));
        arrTrainStation.add(new TrainStation("407", "WALASWEWA"));
        arrTrainStation.add(new TrainStation("301", "WALGAMA"));
        arrTrainStation.add(new TrainStation("303", "WALPOLA"));
        arrTrainStation.add(new TrainStation("306", "WANAWASALA"));
        arrTrainStation.add(new TrainStation("305", "WANDURAWA"));
        arrTrainStation.add(new TrainStation("308", "WATAGODA"));
        arrTrainStation.add(new TrainStation("336", "WATARAKA"));
        arrTrainStation.add(new TrainStation("300", "WATAWALA"));
        arrTrainStation.add(new TrainStation("294", "WATTEGAMA"));
        arrTrainStation.add(new TrainStation("478", "Weligalla"));
        arrTrainStation.add(new TrainStation("302", "WELIGAMA"));
        arrTrainStation.add(new TrainStation("298", "WELIKANDA"));
        arrTrainStation.add(new TrainStation("293", "WELLAWA"));
        arrTrainStation.add(new TrainStation("307", "WELLAWATTA"));
        arrTrainStation.add(new TrainStation("411", "WERAGALA"));
        arrTrainStation.add(new TrainStation("304", "WIJAYARAJADAHANA"));
        arrTrainStation.add(new TrainStation("309", "WILWATTE"));
        arrTrainStation.add(new TrainStation("297", "WLAKUBURA"));
        arrTrainStation.add(new TrainStation("473", "YAGODA"));
        arrTrainStation.add(new TrainStation("387", "YAGODA"));
        arrTrainStation.add(new TrainStation("315", "YAPAHUWA"));
        arrTrainStation.add(new TrainStation("313", "YATAGAMA"));
        arrTrainStation.add(new TrainStation("463", "YATAWARA"));
        arrTrainStation.add(new TrainStation("311", "YATIRAWANA"));
        arrTrainStation.add(new TrainStation("316", "YATTALGODA"));
        return arrTrainStation;
    }
}
